name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: ./rebuild.sh

      - run: ls -l

      - name: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          removeArtifacts: true
          tag: latest
          artifacts: "*.deb"
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: iliabylich/ppa@notify
        with:
          token: ${{ secrets.PPA_TOKEN }}
